version: '3.7'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
      - minio
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    restart: always
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    ports:
      - "5432:5432"

  minio:
    container_name: minio
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.dev
    volumes:
      - minio_data:/var/lib/minio_data/

  redis:
    restart: always
    image: redis:7.0-rc2
    ports:
      - "6379:6379"
    depends_on:
      - web

  celery:
    build: .
    volumes:
      - .:/usr/src/app/
    depends_on:
      - web
      - db
      - redis
    env_file:
      - .env.dev
    command: celery -A task worker --loglevel=info

volumes:
  postgres_data:
  minio_data: